# 1- Importation des librairies pour tester les différents modèles

In [214]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import os

In [171]:
train = pd.read_csv('train_final.csv')

In [172]:
train.set_index('id', inplace = True)

In [196]:
train

duration  credit_amount  installment_commitment  residence_since  \
id                                                                      
30   0.622518       2.010778               -1.754567        -0.727127   
536  1.988249       1.031710                0.017446        -0.727127   
696 -1.312267      -0.132756               -0.868560        -0.727127   
558 -0.060347      -0.837685                0.903452         1.109417   
837 -0.060347      -0.456057                0.903452        -0.727127   
..        ...            ...                     ...              ...   
107  1.305384      -0.203582                0.903452         1.109417   
271  0.622518      -0.189834                0.903452         1.109417   
861 -0.629401      -0.457307                0.017446        -1.645399   
436 -0.743212       0.050559                0.017446        -1.645399   
103 -0.401780      -0.598126                0.903452        -0.727127   

          age  existing_credits  num_dependents  checking_status  employment  \
id                                                                             
30  -0.437229         -0.698918       -0.432410                1           1   
536 -0.641078          1.075834       -0.432410                1           2   
696  0.072394         -0.698918       -0.432410                2           2   
558  0.174318         -0.698918        2.312621                2           4   
837 -1.048776          1.075834       -0.432410                0           2   
..        ...               ...             ...              ...         ...   
107 -1.150701         -0.698918       -0.432410                1           3   
271  0.072394         -0.698918       -0.432410                1           1   
861 -0.641078          1.075834       -0.432410                1           1   
436 -1.048776         -0.698918       -0.432410                3           2   
103  0.887790         -0.698918       -0.432410                0           2   

     savings_status  ...  other_payment_plans_bank  other_payment_plans_none  \
id                   ...                                                       
30                0  ...                         0                         1   
536               1  ...                         0                         1   
696               1  ...                         0                         1   
558               1  ...                         1                         0   
837               1  ...                         0                         1   
..              ...  ...                       ...                       ...   
107               1  ...                         0                         1   
271               1  ...                         0                         1   
861               1  ...                         1                         0   
436               1  ...                         0                         1   
103               1  ...                         0                         1   

     other_payment_plans_stores  housing_for free  housing_own  housing_rent  \
id                                                                             
30                            0                 0            1             0   
536                           0                 0            1             0   
696                           0                 0            1             0   
558                           0                 0            1             0   
837                           0                 0            1             0   
..                          ...               ...          ...           ...   
107                           0                 0            0             1   
271                           0                 0            1             0   
861                           0                 0            1             0   
436                           0                 0            1             0   
103          

# 2- Determination de la target value et split du dataset

In [197]:
y= train['class']
del train['class']
X = train

In [198]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 40)

In [199]:
X_train.shape

(568, 47)

In [200]:
y_train.shape

(568,)

In [201]:
X_test.shape

(143, 47)

In [202]:
y_test.shape

(143,)

# 3- Application de la regression logistique

In [308]:
log = LogisticRegression()
log.fit(X_train, y_train)
y_pred_log = log.predict(X_test)
print(accuracy_score(y_pred_log, y_test))
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

0.6993006993006993
[[15 22]
 [21 85]]
              precision    recall  f1-score   support

           0       0.42      0.41      0.41        37
           1       0.79      0.80      0.80       106

    accuracy                           0.70       143
   macro avg       0.61      0.60      0.60       143
weighted avg       0.70      0.70      0.70       143



# 5- Application du KNN

In [316]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
print(accuracy_score(y_pred_knn, y_test))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

0.7272727272727273
[[12 25]
 [14 92]]
              precision    recall  f1-score   support

           0       0.46      0.32      0.38        37
           1       0.79      0.87      0.83       106

    accuracy                           0.73       143
   macro avg       0.62      0.60      0.60       143
weighted avg       0.70      0.73      0.71       143



# 6- Application de Naive-Bayes

In [391]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)
print(accuracy_score(y_pred_nb, y_test))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

0.6363636363636364
[[16 21]
 [31 75]]
              precision    recall  f1-score   support

           0       0.34      0.43      0.38        37
           1       0.78      0.71      0.74       106

    accuracy                           0.64       143
   macro avg       0.56      0.57      0.56       143
weighted avg       0.67      0.64      0.65       143



# 7- Application du SVM

In [332]:
from sklearn.svm import SVC


svc = SVC(kernel='sigmoid', gamma='auto', C= 1)
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)
print(accuracy_score(y_pred_svc, y_test))
print(confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

0.7412587412587412
[[  0  37]
 [  0 106]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        37
           1       0.74      1.00      0.85       106

    accuracy                           0.74       143
   macro avg       0.37      0.50      0.43       143
weighted avg       0.55      0.74      0.63       143



C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 8- Application de la forêt aléatoire

In [388]:
from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier(max_depth=9, max_features=15, min_samples_leaf=2, n_estimators=25)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print(accuracy_score(y_pred_rf, y_test))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

0.7342657342657343
[[11 26]
 [12 94]]
              precision    recall  f1-score   support

           0       0.48      0.30      0.37        37
           1       0.78      0.89      0.83       106

    accuracy                           0.73       143
   macro avg       0.63      0.59      0.60       143
weighted avg       0.70      0.73      0.71       143



# 9- Application du XGBoost

In [394]:
from xgboost import XGBClassifier

xgb = XGBClassifier(eta=0.19, max_depth=8, n_estimators=150, subsample=0.8, colsample_bytree=1)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)
print(accuracy_score(y_pred_xgb, y_test))
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

C:\Users\HP\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[09:41:06] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0.7272727272727273
[[15 22]
 [17 89]]
              precision    recall  f1-score   support

           0       0.47      0.41      0.43        37
           1       0.80      0.84      0.82       106

    accuracy                           0.73       143
   macro avg       0.64      0.62      0.63       143
weighted avg       0.72      0.73      0.72       143



# 10- Application des réseaux de neurones

In [395]:
from sklearn.neural_network import MLPClassifier

In [399]:
rn = MLPClassifier(solver = 'lbfgs', alpha = 1e-5, hidden_layer_sizes = (15,), random_state = 1)
rn.fit(X_train, y_train)
y_pred_rn = rn.predict(X_test)
print(accuracy_score(y_pred_rn, y_test))
print(confusion_matrix(y_test, y_pred_rn))
print(classification_report(y_test, y_pred_rn))

0.6783216783216783
[[13 24]
 [22 84]]
              precision    recall  f1-score   support

           0       0.37      0.35      0.36        37
           1       0.78      0.79      0.79       106

    accuracy                           0.68       143
   macro avg       0.57      0.57      0.57       143
weighted avg       0.67      0.68      0.68       143

